<?php echo \Phalcon\Tag::stylesheetLink("css/register/index.css"); ?>

<h2>Create Your Own Profile!</h2>

<form action="/questions/register/register" method="post">
    <div class="formRow">
        <label for="username">Username</label>
        <input type="text" name="username" value="" />
    </div>

    <div class="formRow">
        <label for="password">Password</label>
        <input type="password" name="password" value="" />
    </div>

    <div class="formRow">
        <label for="password">Re-enter Password</label>
        <input type="password" name="password2" value="" />
    </div>

    <div class="formRow">
        <button type="submit">Submit</button>
    </div>
</form>
